version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/app
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "8081:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/app
    restart: always
    container_name: ${PROJECT_NAME}-php-fpm
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - laravel

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./:/app
    command: sleep 10000
    container_name: ${PROJECT_NAME}-php-cli
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: ${PROJECT_NAME}-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    networks:
      - laravel

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${PROJECT_NAME}-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
    networks:
      - laravel
networks:
  laravel:
    driver: bridge

volumes:
  mysql: